/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/ford_mustang.glb')
  return (
    <group ref={groupRef} {...props} dispose={null}>
      {nodes.Curve007_1 && nodes.Curve007_1.geometry && (
        <mesh castShadow receiveShadow geometry={nodes.Curve007_1.geometry} material={materials['Material.001']} />
      )}
      {nodes.Curve007_2 && nodes.Curve007_2.geometry && (
        <mesh castShadow receiveShadow geometry={nodes.Curve007_2.geometry} material={materials['Material.002']} />
      )}
    </group>
  )
}

useGLTF.preload('/ford_mustang.glb')